### ISSUE TITLE
Error: Executing construct_features.py

### ISSUE THREAD

**Issue by binfeng** [domantasm96/URL-categorization-using-machine-learning#3]
Hi,

Thanks for the interesting project. When I run `./construct_data.sh`
It has the following issues:

Executing construct_features.py
Traceback (most recent call last):
  File "01_construct_features.py", line 46, in <module>
    df = pd.read_csv(input_path)[['url', 'main_category', 'main_category:confidence']]
  File "/home/alex/dev/URL-categorization-using-machine-learning/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/alex/dev/URL-categorization-using-machine-learning/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1552, in _get_listlike_indexer
    self._validate_read_indexer(
  File "/home/alex/dev/URL-categorization-using-machine-learning/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['url', 'main_category', 'main_category:confidence'], dtype='object')] are in the [columns]"
Executing construct_models.py
2020-07-15 21:41:03.084514
Executing train_models.py

I think the content in `Datasets/URL-categorization-DFE.csv` file is incorrect:
version https://git-lfs.github.com/spec/v1
oid sha256:8b20976058afc5b6a15a7277cf9060c3f9eb4b51e0ac0c854dd55460febaa743
size 5738345

Could you help fix this issue? Thanks!

**Comment by binfeng** [comment]
Never mind, I found it. :)

**Comment by BecketTrotter** [comment]
How did you fix?

**Comment by binfeng** [comment]
In one of the branches, I forgot the link, but you can iterate through it.

**Comment by BecketTrotter** [comment]
thank you @binfeng
